version: "3.5"

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8088:8088"
    depends_on:
      - thesarius_db

  thesarius_db:
    image: postgres
    volumes:
      - thesarius:/var/lib/postgresql
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: thesarius
      POSTGRES_PASSWORD: thesarius
      POSTGRES_DB: thesarius

volumes:
  thesarius: {}