server:
  port: 8088

spring:
  mvc:
    servlet:
      path: /api
  datasource:
    url: jdbc:postgresql://localhost:15432/thesarius
    username: thesarius
    password: thesarius
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true


logging:
  level:
    org.hibernate.SQL: DEBUG
    or.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
